### ISSUE TITLE
Google form for updating the profiles

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/people.ce.pdn.ac.lk#62]
I think people are more likely to update their profiles by filling a google form. We can have both options (github pull req and google form) for every profile. However, we might need to make the google form "login mandatory". 

Also, we will have to update the .md files manually according to the form responses. It won't be a big issue since we will have a dedicated maintainer and the number of update requests per week will be very small.

**Comment by ishanfdo18098** [comment]
> I think people are more likely to update their profiles by filling a google form

I agree

---

> Also, we will have to update the .md files manually according to the form responses.

I guess this can be automated using a python script and GitHub Actions.

---

Is it okay if I use my eng.pdn.ac.lk gmail account to create the google form ?

**Comment by gihanjayatilaka** [comment]
Is it okay if I use my eng.pdn.ac.lk gmail account to create the google form?
Obviously, yes. (but write which account the form belongs to somewhere in the repo documentation)

**Comment by ishanfdo18098** [comment]
I have created the Google Form
https://forms.gle/s2otrv1ifh7kQ3oD9

Does anything need to be changed ?
@NuwanJ

**Comment by NuwanJ** [comment]
@ishanfdo18098 Nice work. 
Done a few tiny updates to the descriptions and added the E-Number field (You may need to change the indexes in the CSV😬 ). I also made a few comments on the Python Script. Can you take a look at it?

**Comment by ishanfdo18098** [comment]
> You may need to change the indexes in the CSV😬

Done be12fa890fb50196d1cfe4c7229fef5839dad553

>  I also made a few comments on the Python Script.

Fixed in 552183708735ade05966bad29fa2ece0800c0c88

> move the Google Form and the Sheet into the following folder in the CE Projects

I have moved the Form and the Sheet to the given folder. But It's not possible to move the images folder to the shared drive. Therefore, I have created a shortcut. 
![image](https://user-images.githubusercontent.com/73381996/147882983-cb24d511-26fc-4e6e-9455-06f2d9c77fc3.png)

**Comment by ishanfdo18098** [comment]
![image](https://user-images.githubusercontent.com/73381996/147894750-1bc21385-681c-4770-b34c-97e31ab2d024.png)

I created a copy of the existing (no permissions to move the existing one to my drive) and added shortcuts into the shared folder.
New form link : https://forms.gle/eor3v3nuf1752DGn7 owned by e18098@eng.pdn.ac.lk

**Comment by NuwanJ** [comment]
https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/2abdb40e008b04fa44ee207b67539af1c41f7f35/pages/documentation/add-a-student-page.html#L15

https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/2abdb40e008b04fa44ee207b67539af1c41f7f35/pages/documentation/add-a-student-page.html#L16

@ishanfdo18098 shall we go with the full page iframes? (like the sample code I sent to you) Otherwise, it may get complicated for users to handle the pages with two scroll bars.

**Comment by ishanfdo18098** [comment]
> it may get complicated for users to handle the pages with two scroll bars.

Is there a way set the height of the iframe automatically so that there is no scrollbar for the iframe ?

**Comment by ishanfdo18098** [comment]
Does the forms load on mobile ?
I get a white blank page when I open these links on mobile.

https://people.ce.pdn.ac.lk/form/student/
https://people.ce.pdn.ac.lk/form/alumni/
